skip:
  file:
    - message-index/CNAME
    - message-index/css/highlight.css
    - message-index/js/highlight.min.js
    - message-index/js/tablefilter.js

    # This one's empty and thus can't end with a newline
    - message-index/messages/S-6602/empty/before/empty.yaml

  extension:
    - .hi
    - .o
    - .png

  dir:
    - message-index/dist-newstyle
    - message-index/_cache
    - message-index/_site
