on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build-and-test:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - name: Install GHC 9.2.5
      run: ghcup install ghc 9.2.5

    - name: Select GHC 9.2.5
      run: ghcup set ghc 9.2.5

    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Read the Cabal cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          message-index/dist-newstyle
        key: cabal-cache-0-${{ hashFiles('message-index/message-index.cabal') }}
        restore-keys: |
          cabal-cache-0

    - name: Update the Cabal index
      run: cabal update

    - name: Build with Hakyll
      working-directory: message-index
      run: cabal run site build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./message-index/_site
