name: HLint

on:
  push:
    paths:
      - 'message-index/site.hs'
    branches:
      - main
  pull_request:
    paths:
      - 'message-index/site.hs'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - name: Check site.hs with hlint
      uses: haskell-actions/hlint-scan@v1
      with:
        path: |
          message-index/site.hs
        hints: message-index/.hlint.yml
