name: Pullrequest CI
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - name: Select GHC 9.2.4
      run: ghcup set 9.2.4

    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Read the Cabal cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          message-index/dist-newstyle
        key: cabal-cache-0-${{ hashFiles('message-index/message-index.cabal') }}
        restore-keys: |
          cabal-cache-0

    - name: Update the Cabal index
      run: cabal update

    - name: Check if site.hs is formatted using ormolu
      uses: mrkkrp/ormolu-action@v6
      with:
        pattern: |
          **/site.hs

    - name: Build with Hakyll
      working-directory: message-index
      run: cabal run site build
